name: demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: fabiooliani.com
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Hello, world DEV!
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: fabiooliani.com
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Hello, world HMG!
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: fabiooliani.com
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Hello, world PRD!
